### ISSUE TITLE
Gulp 4 - Invalid glob argument

### ISSUE THREAD

**Issue by Asoseil** [ck86/main-bower-files#139]
With gulp 4 i encountered this error: 

> Invalid glob argument: at Gulp.src (/node_modules/vinyl-fs/lib/src/index.js:32:11)

I simply called mainBowerFiles()

**Comment by TrySound** [comment]
@Asoseil Show your gulpfile

**Comment by Asoseil** [comment]
http://pastebin.com/GkA7WEwY

**Comment by TrySound** [comment]
@Asoseil And what is the result of `bowerFIles()`?

**Comment by TrySound** [comment]
@Asoseil I think you don't have packages yet.
https://github.com/gulpjs/vinyl-fs/issues/164

**Comment by phated** [comment]
The is the expected behavior with an empty array and we aren't going to change it.

Issues related to this which outline why this is the correct behavior:
* https://github.com/gulpjs/gulp/issues/1298
* https://github.com/gulpjs/vinyl-fs/issues/40
* https://github.com/jonschlinkert/is-valid-glob/issues/3
